import os
import json

def compile_design_tokens():
    print("🎨 Activating Centralized Theme Engine...")
    theme_path = "data/theme.json"
    variables_css_path = "assets/css/theme-variables.css"
    
    # Ensure css asset directory structure exists
    os.makedirs(os.path.dirname(variables_css_path), exist_ok=True)
    
    if not os.path.exists(theme_path):
        print("💥 Design Error: data/theme.json config file not found!")
        return

    with open(theme_path, 'r', encoding='utf-8') as f:
        theme = json.load(f)

    # Building global standard CSS variables mapped to your design blueprint tokens
    css_content = f"""/* 🤖 AUTOGENERATED THEME TOKENS - DO NOT MODIFY DIRECTLY */
:root {{
  --primary: {theme.get('primary_color', '#000000')};
  --secondary: {theme.get('secondary_color', '#000000')};
  --accent: {theme.get('accent_color', '#000000')};
  --bg-main: {theme.get('background_color', '#ffffff')};
  --bg-card: {theme.get('card_background', '#ffffff')};
  --text-main: {theme.get('text_color', '#000000')};
  --font-main: {theme.get('font_family', 'sans-serif')};
}}
"""
    
    with open(variables_css_path, 'w', encoding='utf-8') as f:
        f.write(css_content)
        
    print(f"✅ Design System Synced! Generated variable definitions: {variables_css_path}")

if __name__ == "__main__":
    compile_design_tokens()